const en = {
  swedish: 'Swedish',
  english: 'English',
  general: {
    explore: 'Explore',
    unsavedAlert: 'This page wants you to confirm that you are leaving the page - data may not be saved data',
    save: 'Save',
    preview: 'Preview',
    cancel: 'Cancel',
    name: 'Name',
    back: 'Back',
    section: {
      preamble: 'Preamble',
      TEXT: 'Text section',
      DISTANCE_TABLE: 'Distance table',
      STREET_VIEW: 'Google street view',
      COMMUTE_TIME: 'Travel time and commute',
      HOUSE_LISTINGS: 'Recently listed for sale',
      IMAGES: 'Image carousel',
      edit: 'Edit',
      stopEdit: 'Stop editing',
      remove: 'Remove',
      add: 'Add',
      newSection: 'new section after this one',
    },
    saveSuccess: 'Saved!',
    saveError: 'Something went wrong. Try again later.',
    image: 'Image',
  },
  navigationSideBar: {
    loggedInAs: 'You´re logged in as:',
    mapState: 'Map',
    municipalityOverview: 'About municipality',
    areas: 'Areas',
    media: 'Media library',
    logOut: 'Log out',
    contact: 'Contact',
    settings: 'Settings',
    inactivatedDesc: 'The municipality is disabled.',
    activateContact: 'Contact syssupport@dewire.com when you\'re ready to publish the municipality.',
  },
  areas: {
    title: 'Areas',
    add: 'Add new area',
  },
  inputWithLabel: {
    cannotBeEmpty: 'The field cannot be emtpy',
    cannotBeLessThan: 'The field cannot contain less than ',
    chars: ' characters',
    cannotBeLongerThan: 'The field cannot contain more than ',
    invalidCharacters: 'The field contains invalid characters',
  },
  areaOverview: {
    removeAreYouSurePt1: 'Are you sure you want to remove the area ',
    removeAreYouSurePt2: ' from the service?',
    removeArea: 'Remove area',
    heading: 'Edit area',
    headingAdd: 'Add area',
    areaCardSave: 'Save area',
    changeAreaPos: 'Edit the area placement',
    stopChangeAreaPos: 'Stop editing',
    editingNotice: 'Click on the map to set the area placement',
    areaPicker: {
      heading: 'Copy a pre-existing area',
      description: 'Select the area you want to copy content sections from in the list below. If you don´t want to copy a area and start editing without content sections click ',
      here: 'here',
    },
    areaDetails: {
      mapTitle: 'Map placement',
      commonTitle: 'General information',
      coordinates: {
        title: 'Coordinates',
        lat: 'Latitude',
        lng: 'Longitude',
      },
      thumbnail: 'Thumbnail for area card',
      housingTypes: {
        title: 'Housing types',
        apartment: 'Apartments',
        house: 'Houses',
      },
      nyko: 'Nyckelkodsområde (NYKO)',
    },
    areaOverv: {
      contentTitle: 'Content sections',
      imageCarousel: 'Image carousel top',
      image: 'Image',
    },
  },
  media: {
    heading: 'Media library',
  },
  imageUpload: {
    heading: 'Upload image',
    upload: 'Upload',
    uploadArea: 'Drag image or click to upload',
    previewNoun: 'Preview',
    previewSub: 'Preview',
    crop: 'Crop',
    adjustPicture: 'Edit image',
    errorMsgWrongFormat: 'This file format is not supported, please try again.',
    errorMsgTooLarge: 'The file size exceeds the size limit, please try again.',
    errorMsgOther: 'An unknown error occured, please try again.',
  },
  municipalityPage: {
    aboutMunicipality: 'About municipality',
    aboutService: 'About service',
    chooseLanguage: 'Language',
    start: 'Start',
    explore: 'Explore',
    moveTo: 'Move to ',
  },
  aboutMunicipality: {
    heading: 'Edit About Municipality ',
    information: 'Information',
  },
  mapState: {
    heading: 'Edit map parameters',
    mapPlacement: 'Map placement',
    mapPlacementDesc: 'Here is where you change the municipality´s initial map. Click the "Change map placement" button below to start editing the map. After this you can adjust the map placement and zoom level. You can also click on the map to change the commute destination.',
    startMap: 'Initial map',
    zoom: 'Zoom level',
    commuteDestination: 'Commute destination',
    changeMapPos: 'Change the map placement',
    editingNoticeCommute: 'Click on the map to select the commute destination,',
    editingNoticeMapState: 'Move the map and change the zoom level to decide the initial map,',
    coordinates: {
      title: 'Coordinates',
      lat: 'Latitude',
      lng: 'Longitude',
    },
  },
  startPage: {
    headingStart: 'Edit start page',
    headingContact: 'Edit contact',
    save: 'Save start page',
    preview: 'Preview',
    swedishPreamble: 'Swedish preamble',
    englishPreamble: 'English preamble',
    edit: 'Edit',
    stopEdit: 'Quit editing',
    swedishContact: 'Swedish contact text',
    englishContact: 'English contact text',
    backgroundImage: 'Background image',
    logo: 'Logo',
    pictures: 'Pictures',
    email: 'Email address',
    mailBtn: 'Email me',
    mailSubject: 'Välkommen hit contact form',
  },
  imagePicker: {
    chooseAImage: 'Choose a image',
    removeAreYouSurePt1: 'Are you sure you want to remove the image ',
    removeAreYouSurePt2: ' from the media library?',
  },
  tabContact: {
    contact: 'Contact',
    mailBtn: 'Email me',
    contactPicture: 'Contact picture',
    svEmailBtn: 'Swedish button text',
    enEmailBtn: 'English button text',
  },
  theme: {
    header: 'Choose color theme',
    green: 'Green',
    orange: 'Orange',
    blue: 'Blue',
  },
  admin: {
    enabled: 'Enabled',
    disabled: 'Disabled',
    lantmateriet: 'Lantmäteriet',
    username: 'Username',
    password: 'Password',
    editable: 'Editable',
    addMunicipality: 'Add new municipality',
    user: 'User',
    addUser: 'Add user',
    saveUser: 'Save user',
    userGroup: 'User group',
    email: 'Email address',
    emailError: 'Not a valid email address',
    municipality: 'Municipality',
  },
};

export default en;
