const sv = {
  swedish: 'Svenska',
  english: 'English',
  general: {
    explore: 'Utforska',
    unsavedAlert: 'Den här sidan vill att du bekräftar att du vill lämna sidan - data som du har skrivit in kanske inte sparas',
    save: 'Spara',
    preview: 'Förhandsgranska',
    cancel: 'Avbryt',
    name: 'Namn',
    back: 'Tillbaka',
    section: {
      preamble: 'Ingress',
      TEXT: 'Text-sektion',
      DISTANCE_TABLE: 'Avståndstabell',
      STREET_VIEW: 'Google street view',
      COMMUTE_TIME: 'Restid och pendlingsavstånd',
      HOUSE_LISTINGS: 'Nyligen utlagt till försäljning',
      IMAGES: 'Bildkarusell',
      edit: 'Redigera',
      stopEdit: 'Sluta redigera',
      remove: 'Ta bort',
      add: 'Lägg till',
      newSection: 'ny sektion efter denna',
    },
    saveSuccess: 'Sparat!',
    saveError: 'Något gick fel! Försök igen senare.',
    image: 'Bild',
    noPageHeaderSv: 'Sidan kunde inte hittas (Fel 404)',
    noPageHeaderEn: 'Page not found (Error 404)',
    noPageMessageSv: 'Något gick fel när sidan skulle besökas, vänligen kontrollera angiven länk, språk och kommun.',
    noPageMessageEn: 'Something went wrong when visiting the site, please check link, language and municipality.',
  },
  navigationSideBar: {
    loggedInAs: 'Du är nu inloggad som:',
    mapState: 'Karta',
    municipalityOverview: 'Om kommunen',
    areas: 'Områden',
    media: 'Mediabibliotek',
    logOut: 'Logga ut',
    contact: 'Kontakt',
    settings: 'Inställningar',
    inactivatedDesc: 'Kommunen är inaktiverad.',
    activateContact: 'Kontakta syssupport@dewire.com när ni är redo att publicera kommunen för externa användare.',
  },
  areas: {
    title: 'Områden',
    add: 'Lägg till nytt område',
  },
  inputWithLabel: {
    cannotBeEmpty: 'Fältet får inte vara tomt',
    cannotBeLessThan: 'Fältet får innehålla färre än ',
    chars: ' tecken',
    cannotBeLongerThan: 'Fältet får inte innehålla fler än ',
    invalidCharacters: 'Fältet innehåller ogiltiga tecken',
  },
  areaOverview: {
    removeAreYouSurePt1: 'Är du säker på att du vill ta bort området ',
    removeAreYouSurePt2: ' från tjänsten?',
    removeArea: 'Ta bort område',
    headingEdit: 'Redigera område',
    headingAdd: 'Lägg till område',
    areaCardSave: 'Spara område',
    changeAreaPos: 'Ändra områdets placering',
    stopChangeAreaPos: 'Avsluta redigering',
    editingNotice: 'Klicka på kartan för att välja områdets placering',
    areaPicker: {
      heading: 'Kopiera ett existerande område',
      description: 'Välj det område du vill kopiera innehållssektioner från i listan nedan. Ifall du inte vill kopiera ett område och börja utan innehållssektioner klicka ',
      here: 'här',
    },
    areaDetails: {
      mapTitle: 'Kartplacering',
      commonTitle: 'Allmän information',
      name: 'Namn',
      coordinates: {
        title: 'Koordinater',
        lat: 'Latitud',
        lng: 'Longitud',
      },
      thumbnail: 'Bild till områdeskort',
      housingTypes: {
        title: 'Boendetyper',
        apartment: 'Lägenheter',
        house: 'Hus',
      },
      nyko: 'Nyckelkodsområde (NYKO)',
    },
    areaOverv: {
      contentTitle: 'Innehållssektioner',
      imageCarousel: 'Bildkarusell topp',
      image: 'Bild',
    },
  },
  media: {
    heading: 'Mediabibliotek',
  },
  imageUpload: {
    heading: 'Ladda upp bild',
    upload: 'Ladda upp',
    uploadArea: 'Dra hit en fil eller klicka för att ladda upp',
    previewNoun: 'Förhandsgranska',
    previewSub: 'Förhandsgranskning',
    crop: 'Beskär',
    adjustPicture: 'Anpassa bilden',
    errorMsgWrongFormat: 'Filformatet stöds inte, vänligen kontrollera detta och försök igen.',
    errorMsgTooLarge: 'Filen är för stor, vänligen kontrollera detta och försök igen.',
    errorMsgOther: 'Ett okänt fel inträffade, vänligen försök igen.',
  },
  municipalityPage: {
    aboutMunicipality: 'Om kommunen',
    aboutService: 'Om tjänsten',
    chooseLanguage: 'Language',
    start: 'Start',
    moveTo: 'Flytta till ',
  },
  aboutMunicipality: {
    heading: 'Redigera Om kommunen',
    information: 'Information',
  },
  mapState: {
    heading: 'Redigera kartparametrar',
    mapPlacement: 'Kartplacering',
    mapPlacementDesc: 'Här kan du ändra kommunens ursprungliga karta. Klicka på "Ändra kartans placering" nedan för att börja redigera kartan, efter detta så kan du justera kartans placering och zoom-nivå. Du kan även klicka på kartan för att flytta den ursprungliga pendlingsdestinationen. ',
    startMap: 'Startkarta',
    zoom: 'Zoomnivå',
    commuteDestination: 'Pendlingsdestination',
    changeMapPos: 'Ändra kartans placering',
    editingNoticeCommute: 'Klicka på kartan för att välja pendlingsdestinationens placering,',
    editingNoticeMapState: 'Flytta kartan och ändra zoomnivå för att bestämma kommunens startkarta',
    coordinates: {
      title: 'Koordinater',
      lat: 'Latitud',
      lng: 'Longitud',
    },
  },
  startPage: {
    headingStart: 'Redigera startsida',
    headingContact: 'Redigera kontakt',
    save: 'Spara startsida',
    preview: 'Förhandsgranskning',
    swedishPreamble: 'Svensk ingress',
    englishPreamble: 'Engelsk ingress',
    edit: 'Redigera',
    stopEdit: 'Sluta redigera',
    swedishContact: 'Svensk kontakttext',
    englishContact: 'Engelsk kontakttext',
    backgroundImage: 'Bakgrundsbild',
    logo: 'Logotyp',
    pictures: 'Bilder',
    email: 'E-postadress',
    mailBtn: 'Maila mig',
    mailSubject: 'Välkommen hit kontaktformulär',
  },
  imagePicker: {
    chooseAImage: 'Välj en bild',
    removeAreYouSurePt1: 'Är du säker på att du vill ta bort bilden ',
    removeAreYouSurePt2: ' från mediabiblioteket?',
  },
  tabContact: {
    contact: 'Kontakt',
    contactPicture: 'Kontaktbild',
    mailBtn: 'Maila mig',
    svEmailBtn: 'Svensk knapptext',
    enEmailBtn: 'Engelsk knapptext',
  },
  theme: {
    header: 'Välj färgtema',
    green: 'Grönt',
    orange: 'Orange',
    blue: 'Blått',
  },
  admin: {
    enabled: 'Aktiverad',
    disabled: 'Avaktiverad',
    lantmateriet: 'Lantmäteriet',
    username: 'Användarnamn',
    password: 'Lösenord',
    editable: 'Redigerbar',
    addMunicipality: 'Lägg till ny kommun',
    user: 'Användare',
    addUser: 'Lägg till användare',
    saveUser: 'Spara användare',
    userGroup: 'Användargrupp',
    email: 'E-postadress',
    emailError: 'Inte en giltig e-postadress',
    municipality: 'Kommun',
  },
  editor:
  {
    // Generic
    'generic.add': 'Lägg till ',
    'generic.cancel': 'Avbryt',

    // History
    'components.controls.history.history': 'Historik',
    'components.controls.history.undo': 'Ångra',
    'components.controls.history.redo': 'Gör om',

    // Inline
    'components.controls.inline.bold': 'Fetstil',
    'components.controls.inline.italic': 'Kursiv',
    'components.controls.inline.underline': 'Understruken',

    // Link
    'components.controls.link.linkTitle': 'Titel',
    'components.controls.link.linkTarget': 'Mål',
    'components.controls.link.linkTargetOption': 'Öppna i nytt fönster',
    'components.controls.link.link': 'Länka',
    'components.controls.link.unlink': 'Ta bort länk',

    // List
    'components.controls.list.list': 'Lista',
    'components.controls.list.unordered': 'Punktlista',
  },
};

export default sv;
